### PR TITLE
Update bower.json to add wiredep inclusion

### PR DESCRIPTION
**Pull request by spaceribs**
See: https://github.com/taptapship/wiredep#what-can-go-wrong

### CODE REVIEW

**Comment by mbrandorff** [comment]
was just about to make a pull request for this one, too. :) :+1:

**Comment by spaceribs** [comment]
Great minds etc. etc.

Paging @olivierbossel on this

**Comment by rafegoldberg** [comment]
:+1: for `wiredep` inclusion via bower; would be v. useful!

**Comment by olivierbossel** [comment]
This will be fixed in 2.0.4 version.
Thanks for your time guys!

**Pull request closed without merging**
